SET DEFINE OFF;
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (50, 41, 100, 1, 2017, 
    3, 0, 1, 19, 'EGP', 
    'مصر', 'Asset Technology', 0, 1200, 100, 
    'EGP');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (51, 41, 100, 2, 2017, 
    12, 5100, 1, 19, 'EGP', 
    'مصر', 'Asset Technology', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (52, 1, 100, 2, 2017, 
    1, 100, 100, 22, 'IQD', 
    'أفغانستان', 'hassanain company', 0, 150, 111, 
    'IQD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (53, 1, 101, 4, 2017, 
    1, 50, 937.5, 22, 'IQD', 
    'أفغانستان', 'hassanain company', 0, 1200, 100, 
    'EGP');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (54, 1, 111, 5, 2017, 
    5, 0, 120, 22, 'IQD', 
    'أفغانستان', 'hassanain company', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (55, 130, 100, 6, 2017, 
    1, 500, 1, 64, 'EGP', 
    'الإمارات العربية المتحدة', 'Ansary Company', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (56, 1, 100, 5, 2017, 
    32, 3050, 3050, 22, 'IQD', 
    'أفغانستان', 'hassanain company', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (57, 41, 111, 8, 2017, 
    5, 0, 120, 19, 'IQD', 
    'مصر', 'Asset Technology', 1, 200, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (58, 1, 100, 9, 2017, 
    5, 113, 1, 22, 'EGP', 
    'أفغانستان', 'hassanain company', 1, 250, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (59, 1, 100, 10, 2017, 
    9, 500, 1, 19, 'EGP', 
    'أفغانستان', 'Asset Technology', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (60, 1, 100, 11, 2017, 
    10, 1500, 1500, 19, 'IQD', 
    'أفغانستان', 'Asset Technology', 0, 170, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (202, 41, 103, 5, 2021, 
    1, 500, 19, 'AUD', 
    'مصر', 'Asset Technology', 1, 9, 101, 'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (203, 41, 100, 5, 2021, 
    1, 500, 19, 'EGP', 
    'مصر', 'Asset Technology', 0, 9, 102, 'AED');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (61, 1, 100, 11, 2016, 
    1, 500, 500, 64, 'EGP', 
    'أفغانستان', 'Ansary Company', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (67, 130, 101, 11, 2017, 
    50, 9500, 1500, 19, 'USD', 
    'أفغانستان', 'Asset Technology', 0, 170, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (66, 130, 101, 11, 2016, 
    30, 11500, 500, 1, 'USD', 
    'أفغانستان', 'Ansary Company', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (65, 130, 100, 11, 2016, 
    20, 600, 500, 64, 'EGP', 
    'أفغانستان', 'Ansary Company', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (64, 130, 100, 11, 2017, 
    20, 2500, 1500, 19, 'IQD', 
    'أفغانستان', 'Asset Technology', 0, 170, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (62, 1, 101, 11, 2016, 
    30, 9500, 500, 1, 'USD', 
    'أفغانستان', 'Ansary Company', 1, 100, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, EQ_IN_1000EGP, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (63, 1, 101, 11, 2017, 
    50, 8500, 1500, 19, 'USD', 
    'أفغانستان', 'Asset Technology', 0, 170, 101, 
    'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (201, 41, 100, 5, 2021, 
    1, 500, 19, 'EGP', 
    'مصر', 'Asset Technology', 0, 9, 101, 'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (204, 41, 103, 5, 2021, 
    2, 1000, 19, 'AUD', 
    'الإمارات العربية المتحدة', 'Asset Technology', 1, 18, 101, 'USD');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE, COMPANY_COMMISSION_AMOUNT, COMPANY_COMMISSION_CURRENCY_ID, COMPANY_COMMISSION_CURR_ACRO)
 Values
   (205, 41, 100, 5, 2021, 
    1, 500, 19, 'EGP', 
    'مصر', 'Asset Technology', 0, 9, 102, 'AED');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME)
 Values
   (151, 41, 100, 5, 2021, 
    1, 500, 19, 'EGP', 
    'مصر', 'Asset Technology');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME)
 Values
   (152, 41, 100, 5, 2021, 
    1, 500, 19, 'EGP', 
    'مصر', 'Asset Technology');
Insert into MONTHLY_REPORT
   (ID, COUNTRY_ID, CURRENCY_ID, MONTH, YEAR, COUNTS, AMOUNT, COMPANY_ID, CURRENCY_ACRONYM, COUNTRY_NAME, COMPANY_NAME, REM_TYPE)
 Values
   (153, 41, 100, 5, 2021, 
    1, 500, 19, 'EGP', 
    'مصر', 'Asset Technology', 0);
COMMIT;
